"""remove_embedding_hash_unique

Revision ID: e4852f79f071
Revises: f3040982039a
Create Date: 2026-08-12 00:31:35.651475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4852f79f071'
down_revision: Union[str, Sequence[str], None] = 'f3040982039a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_memory_chunks_hash'), 'memory_chunks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_memory_chunks_hash'), 'memory_chunks', ['embedding_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
