"""Add MemoryChunk and EmbeddingJob

Revision ID: f3040982039a
Revises: 085814ce8a85
Create Date: 2026-08-11 23:56:50.074630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3040982039a'
down_revision: Union[str, Sequence[str], None] = '085814ce8a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_jobs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_embedding_jobs_source', 'embedding_jobs', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_embedding_jobs_status'), 'embedding_jobs', ['status'], unique=False)
    op.create_table('memory_chunks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('text_chunk', sa.Text(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embedding_hash', name='uq_memory_chunks_hash')
    )
    op.create_index(op.f('ix_memory_chunks_embedding_hash'), 'memory_chunks', ['embedding_hash'], unique=False)
    op.create_index('ix_memory_chunks_source', 'memory_chunks', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_memory_chunks_source_id'), 'memory_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_memory_chunks_source_type'), 'memory_chunks', ['source_type'], unique=False)
    op.add_column('messages', sa.Column('needs_embedding', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_messages_needs_embedding'), 'messages', ['needs_embedding'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_needs_embedding'), table_name='messages')
    op.drop_column('messages', 'needs_embedding')
    op.drop_index(op.f('ix_memory_chunks_source_type'), table_name='memory_chunks')
    op.drop_index(op.f('ix_memory_chunks_source_id'), table_name='memory_chunks')
    op.drop_index('ix_memory_chunks_source', table_name='memory_chunks')
    op.drop_index(op.f('ix_memory_chunks_embedding_hash'), table_name='memory_chunks')
    op.drop_table('memory_chunks')
    op.drop_index(op.f('ix_embedding_jobs_status'), table_name='embedding_jobs')
    op.drop_index('ix_embedding_jobs_source', table_name='embedding_jobs')
    op.drop_table('embedding_jobs')
    # ### end Alembic commands ###
